# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from collections import Counter

texto = "chatbot chatbot inteligência artificial chatbot aprendizado"

# TODO: transformar texto em lista de palavras
# O método .split() quebra a string nos espaços em branco
palavras = texto.split()

# TODO: calcular frequência
# O Counter cria um dicionário contando as ocorrências de cada item na lista
frequencia = Counter(palavras)

print(frequencia)

# Resultado esperado: Counter({'chatbot': 3, 'inteligência': 1, 'artificial': 1, 'aprendizado': 1})

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

frases = [
    "quero comprar produto",
    "desejo fazer compra",
    "quero cancelar pedido",
    "cancelar minha compra",
    "qual horário funcionamento",
    "vocês abrem sábado"
]

intencoes = [
    "comprar",
    "comprar",
    "cancelar",
    "cancelar",
    "horario",
    "horario"
]

# TODO criar vetorizador
# O CountVectorizer transforma texto em números (frequência de palavras)
vetorizador = CountVectorizer()

# TODO transformar frases em vetores
# fit_transform aprende as palavras e já converte as frases da lista
X = vetorizador.fit_transform(frases)

# TODO treinar modelo Naive Bayes
# Criamos o classificador e treinamos (fit) com os dados (X) e as etiquetas (intencoes)
modelo = MultinomialNB()
modelo.fit(X, intencoes)

# TODO pedir frase do usuário
entrada = input("Digite sua mensagem: ")

# TODO transformar entrada em vetor
# Importante: usamos apenas .transform() para usar o padrão que o modelo já conhece
entrada_vetor = vetorizador.transform([entrada])

# TODO prever intenção
# O modelo olha para o vetor da entrada e decide qual a intenção mais provável
predicao = modelo.predict(entrada_vetor)

print("Intenção detectada:", predicao[0])